steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=.
      - --image=gcr.io/$PROJECT_ID/notes-api:$COMMIT_SHA
      - --location=us-central1
      - --cluster=my-cluster

options:
  machineType: "N1_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
  
logging:
  name: "Notes API Deployment"
  description: "Cloud Build for Notes API service"
